FROM ubuntu:22.04

# Set environment variables to prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y \
    iproute2 \
    net-tools \
    python3-numpy \
    iputils-ping \
    tcpdump \
    netcat \
    python3 \
    python3-pandas \
    python3-scipy \
    python3-matplotlib \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY receiver.py .

# Set a default value for DATA_DIR
ENV DATA_DIR=/data

# Create the directory
RUN mkdir -p $DATA_DIR

# Make sure the directory is writable
RUN chmod 777 $DATA_DIR

CMD ["python3", "receiver.py"]